apiVersion: v1
data:
  password: bWluaGEtc2VuaGEtZG8tYWlyZmxvdy0xNzg4
  postgres-password: bWluaGEtc2VuaGEtZG8tcG9zdGdyZXMtMTc4OA==
  replication-password: bWluaGEtc2VuaGEtZGUtcmVwbGljYW8tMTc4OA==
kind: Secret
metadata:
  name: airflow-postgresql-credentials
  namespace: airflow